# Generated by Django 2.1.7 on 2019-03-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_comment', '0002_auto_20190307_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='usr_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment_score',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='comment_score',
            name='score_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(null=True),
        ),
    ]
